---
title: "Assignment Part III"
author: "Silpa Soni Nallacheruvu (19980824-5287)"
date: "`r Sys.Date()`"
output: pdf_document
---

set.seed(980824)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=FALSE}
source("../Codes/Functions.R")
code <- readLines("codes_assignment_3.R")
eval(parse(text = code[6:100]))
```

# Summary


# Task 1

## Approach :


## Code :

```{r echo=TRUE}
# ---- Task_1 ----

# Compute AIC = 2k - 2l(theta_ml)
n <- nrow(X)
theta0 = rep(0, ncol(X))
k <- length(theta0)
theta_estimate <- NR(theta0, 3, y, X) 
l <- l(theta_estimate, y, X)
aic_computed <- 2*k - 2*l

#AIC output from R summary 
r_summary_aic <- summary(modell)$aic

# Compute n*k_cv = l(theta_ml) + sum((S_i(theta_i))T*(theta_i - theta_ml))
# Here, theta_i = theta_ml(X_-i)
nk_cv <- l
for(i in 1:n) {
  X_minus_i <- X[-i, , drop=FALSE]
  y_minus_i <- y[-i, , drop=FALSE]
  theta_i <- NR(theta0, 3, y_minus_i, X_minus_i)
  score <- S(theta_i, y_minus_i, X_minus_i)
  subset_sum <- t(score) %*% (theta_i - theta_estimate)
  nk_cv <- nk_cv + subset_sum
}

# Creating a comparison data frame 
comparison_aic_values <- data.frame(
  "AIC_R_model" = r_summary_aic,
  "AIC_computed" = aic_computed,
  "NKCV_computed" = -2*nk_cv
)

```

## Output :


```{r}

```

## Observation :

# Task 2

## Approach :



## Code :

```{r echo=TRUE}
# ---- Task_2 ----


```

## Output :



```{r}

```

## Observation :


# Task 3

## Approach :



## Code :

```{r echo=TRUE}
# ---- Task_3 ----


```

## Output :



```{r}

```

## Observation :


